"""
import_dem.py — Import a 16-bit grayscale heightmap PNG as terrain mesh in Blender.

Part of the Ellensburg Golf Club GS Pro course build pipeline.
Pipeline stage: LIDAR → QGIS → heightmap PNG → THIS SCRIPT → Blender terrain

Usage:
    1. Open Blender (3.x or 4.x)
    2. Go to Scripting workspace
    3. Open this file or paste into a new text block
    4. Press "Run Script"
    5. A file dialog will open — select your heightmap PNG
    6. The script looks for a matching metadata JSON in the same directory
       (e.g., heightmap.png → heightmap_metadata.json)

The metadata JSON should contain (generated by the LIDAR pipeline):
    {
        "real_width_m": 800.0,
        "real_height_m": 600.0,
        "elevation_min": 460.2,
        "elevation_max": 468.5,
        "pixel_size": 0.5,
        "crs": "EPSG:32610",
        "source": "WA_DNR_LIDAR"
    }

If no metadata JSON is found, the script uses sensible defaults for
Ellensburg Golf Club (approx 800m x 600m, ~10m elevation range).
"""

import bpy
import bmesh
import os
import json
import math
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration — adjust these if you're not using the metadata JSON
# ---------------------------------------------------------------------------

# Default values used when no metadata JSON is found.
# These are reasonable estimates for Ellensburg Golf Club.
DEFAULTS = {
    "real_width_m": 800.0,       # East-west extent in meters
    "real_height_m": 600.0,      # North-south extent in meters
    "elevation_min": 460.0,      # Minimum elevation in meters (~1510 ft)
    "elevation_max": 470.0,      # Maximum elevation in meters (~1542 ft)
    "pixel_size": 0.5,           # Meters per pixel in the heightmap
}

# Subdivision level controls terrain detail.
# For a 4096x4096 heightmap, 12 subdivisions gives 4096 vertices per side.
# For a 2048x2048 heightmap, 11 subdivisions is sufficient.
# Higher = more detail but slower. The script auto-calculates from image size.
SUBDIVISION_OVERRIDE = None  # Set to an integer (e.g., 10) to force a level

# Blender units: 1 Blender unit = 1 meter (GS Pro convention)
SCALE_FACTOR = 1.0

# Vertical exaggeration — set > 1.0 to make elevation changes more visible
# during modeling. Set back to 1.0 before final export.
VERTICAL_EXAGGERATION = 1.0


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def load_metadata(heightmap_path):
    """
    Look for a metadata JSON file alongside the heightmap.
    Tries: <name>_metadata.json, <name>.json, metadata.json in same dir.
    Returns a dict of metadata or DEFAULTS if not found.
    """
    heightmap_path = Path(heightmap_path)
    stem = heightmap_path.stem
    parent = heightmap_path.parent

    # The heightmap PNG often carries a resolution suffix (e.g. "_4096")
    # that the metadata file does not. Strip a trailing "_<digits>" so we
    # can also match e.g. "..._heightmap_meta.json" from "..._heightmap_4096.png".
    base = re.sub(r"_\d+$", "", stem)

    candidates = [
        parent / f"{stem}_meta.json",
        parent / f"{stem}_metadata.json",
        parent / f"{stem}.json",
        parent / f"{base}_meta.json",
        parent / f"{base}_metadata.json",
        parent / f"{base}.json",
        parent / "metadata.json",
        parent / "dem_metadata.json",
    ]

    # Last-resort fallback: any *_meta.json / *_metadata.json in the directory.
    candidates += sorted(parent.glob("*_meta.json"))
    candidates += sorted(parent.glob("*_metadata.json"))

    for candidate in candidates:
        if candidate.exists():
            print(f"[import_dem] Found metadata: {candidate}")
            with open(candidate, 'r') as f:
                data = json.load(f)
            # Normalize key names from the LIDAR pipeline's JSON schema
            # to the names this script expects internally. This MUST run
            # before merging with DEFAULTS — otherwise DEFAULTS would
            # already populate the target keys and the real values from
            # the JSON would never override them.
            KEY_MAP = {
                "real_world_width_m":  "real_width_m",
                "real_world_height_m": "real_height_m",
                "elevation_min_m":     "elevation_min",
                "elevation_max_m":     "elevation_max",
            }
            for old, new in KEY_MAP.items():
                if old in data and new not in data:
                    data[new] = data[old]
            # Merge with defaults so missing keys don't crash
            merged = {**DEFAULTS, **data}
            return merged

    print("[import_dem] No metadata JSON found, using defaults for Ellensburg GC")
    return DEFAULTS.copy()


def calculate_subdivisions(image_width, image_height):
    """
    Calculate the optimal subdivision level for the terrain mesh.
    We want roughly 1 vertex per pixel, but cap at a reasonable maximum.
    Subdivision level N gives 2^N + 1 vertices per side.
    """
    if SUBDIVISION_OVERRIDE is not None:
        return SUBDIVISION_OVERRIDE

    max_dim = max(image_width, image_height)

    if max_dim <= 0:
        print("[import_dem] WARNING: image size is 0x0 (lazy load) — defaulting to subdivision level 10")
        return 10

    # Find the subdivision level that gives us close to the image resolution
    # but cap at 12 (4096 verts per side) to keep Blender responsive
    level = max(4, min(12, int(math.log2(max_dim))))

    print(f"[import_dem] Image size: {image_width}x{image_height}")
    print(f"[import_dem] Using subdivision level: {level} ({2**level + 1} verts/side)")
    return level


def cleanup_existing():
    """Remove any existing terrain objects from previous imports."""
    for obj_name in ["Terrain", "TerrainGrid", "ScaleMarker_X", "ScaleMarker_Y",
                     "ElevationMarker_Low", "ElevationMarker_High"]:
        if obj_name in bpy.data.objects:
            obj = bpy.data.objects[obj_name]
            bpy.data.objects.remove(obj, do_unlink=True)

    # Also remove orphaned meshes
    for mesh in bpy.data.meshes:
        if mesh.name.startswith("Terrain") and mesh.users == 0:
            bpy.data.meshes.remove(mesh)


def create_terrain_plane(meta):
    """
    Create a subdivided plane sized to match the real-world dimensions.
    Returns the terrain object.
    """
    width = meta["real_width_m"] * SCALE_FACTOR
    height = meta["real_height_m"] * SCALE_FACTOR

    # Create a plane. In Blender, a plane is 2x2 units by default,
    # so we scale it to our real dimensions.
    bpy.ops.mesh.primitive_plane_add(
        size=1.0,
        location=(width / 2, height / 2, 0),  # Center the plane
        enter_editmode=False,
    )

    terrain = bpy.context.active_object
    terrain.name = "Terrain"
    terrain.data.name = "TerrainMesh"

    # Scale to real-world dimensions
    terrain.scale = (width, height, 1.0)

    # Apply the scale so the mesh data has the correct coordinates
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)

    return terrain


def subdivide_terrain(terrain, level):
    """
    Subdivide the terrain mesh to create enough geometry for displacement.
    Uses a Subdivision Surface modifier for clean, even subdivision.
    """
    # Add a subdivision surface modifier
    # We use "SIMPLE" mode (not Catmull-Clark) to keep the grid flat
    subsurf = terrain.modifiers.new(name="Subdivide", type='SUBSURF')
    subsurf.subdivision_type = 'SIMPLE'
    subsurf.levels = level           # Viewport subdivision
    subsurf.render_levels = level    # Render subdivision

    # Apply the modifier to bake the geometry into the mesh
    # This is necessary before we can apply the displacement texture
    bpy.context.view_layer.objects.active = terrain
    bpy.ops.object.modifier_apply(modifier="Subdivide")

    vert_count = len(terrain.data.vertices)
    print(f"[import_dem] Terrain mesh has {vert_count:,} vertices after subdivision")
    return vert_count


def load_heightmap_image(filepath):
    """
    Load the heightmap PNG into Blender's image system.
    Returns the Blender image data block.
    """
    # Check if image is already loaded
    img_name = Path(filepath).name
    if img_name in bpy.data.images:
        bpy.data.images.remove(bpy.data.images[img_name])

    img = bpy.data.images.load(filepath)
    img.colorspace_settings.name = 'Non-Color'  # Heightmaps are data, not color

    print(f"[import_dem] Loaded heightmap: {img.size[0]}x{img.size[1]} pixels")
    return img


def apply_displacement_texture(terrain, heightmap_img, meta):
    """
    Apply the heightmap as a displacement texture to deform the terrain mesh.
    This uses Blender's texture displacement (not shader-based) for actual
    geometry deformation that exports correctly.
    """
    elev_range = meta["elevation_max"] - meta["elevation_min"]
    displacement_strength = elev_range * SCALE_FACTOR * VERTICAL_EXAGGERATION

    print(f"[import_dem] Elevation range: {elev_range:.1f}m")
    print(f"[import_dem] Displacement strength: {displacement_strength:.1f} Blender units")

    # Create a texture for the displacement
    tex_name = "HeightmapDisplacement"
    if tex_name in bpy.data.textures:
        bpy.data.textures.remove(bpy.data.textures[tex_name])

    tex = bpy.data.textures.new(tex_name, type='IMAGE')
    tex.image = heightmap_img

    # Add a Displace modifier to the terrain
    displace = terrain.modifiers.new(name="Heightmap", type='DISPLACE')
    displace.texture = tex
    displace.texture_coords = 'UV'    # Use UV coordinates for texture mapping
    displace.direction = 'Z'          # Displace only vertically
    displace.strength = displacement_strength
    displace.mid_level = 0.0          # Black = no displacement, white = full

    # Ensure the terrain has UV coordinates that match the texture
    # The default plane UV should work, but let's make sure
    if not terrain.data.uv_layers:
        terrain.data.uv_layers.new(name="HeightmapUV")

    # Set the base Z position to the minimum elevation
    terrain.location.z = meta["elevation_min"] * SCALE_FACTOR

    return displace


def apply_displacement_via_vertices(terrain, heightmap_img, meta):
    """
    Alternative displacement method: directly modify vertex positions.
    This is more reliable for export and doesn't depend on modifiers.
    Use this if the modifier-based approach causes issues.
    """
    import numpy as np

    elev_range = meta["elevation_max"] - meta["elevation_min"]
    elev_min = meta["elevation_min"] * SCALE_FACTOR
    width = meta["real_width_m"] * SCALE_FACTOR
    height = meta["real_height_m"] * SCALE_FACTOR

    # Get image pixels as a flat array
    img_w, img_h = heightmap_img.size
    pixels = list(heightmap_img.pixels)

    # For a grayscale image loaded as RGBA, every 4th value is the same
    # Channel layout: R, G, B, A — we only need R (or any channel)
    channels = 4
    pixel_count = img_w * img_h

    mesh = terrain.data

    for vert in mesh.vertices:
        # Convert vertex XY position to UV coordinates (0-1 range)
        u = vert.co.x / width
        v = vert.co.y / height

        # Clamp to valid range
        u = max(0.0, min(1.0, u))
        v = max(0.0, min(1.0, v))

        # Convert UV to pixel coordinates
        px = int(u * (img_w - 1))
        py = int(v * (img_h - 1))

        # Look up the pixel value (using R channel)
        pixel_index = (py * img_w + px) * channels
        height_value = pixels[pixel_index]  # 0.0 to 1.0

        # Convert to real elevation
        vert.co.z = elev_min + (height_value * elev_range * SCALE_FACTOR * VERTICAL_EXAGGERATION)

    mesh.update()
    print(f"[import_dem] Applied vertex displacement to {len(mesh.vertices):,} vertices")


def setup_terrain_material(terrain, heightmap_img, meta):
    """
    Create a basic material for the terrain that shows elevation via color ramp.
    This is just for visualization during modeling — the real materials come
    from materials.py later in the pipeline.
    """
    mat_name = "TerrainPreview"
    if mat_name in bpy.data.materials:
        bpy.data.materials.remove(bpy.data.materials[mat_name])

    mat = bpy.data.materials.new(name=mat_name)
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links

    # Clear default nodes
    nodes.clear()

    # Create nodes for an elevation-based color ramp
    # Texture Coordinate → Separate XYZ (get Z) → Map Range → Color Ramp → Principled BSDF

    output = nodes.new('ShaderNodeOutputMaterial')
    output.location = (600, 0)

    bsdf = nodes.new('ShaderNodeBsdfPrincipled')
    bsdf.location = (300, 0)
    bsdf.inputs['Roughness'].default_value = 0.8

    color_ramp = nodes.new('ShaderNodeValToRGB')
    color_ramp.location = (0, 0)
    # Set up a green terrain color ramp (low=dark, high=light)
    ramp = color_ramp.color_ramp
    ramp.elements[0].color = (0.15, 0.3, 0.1, 1.0)   # Dark green (low areas)
    ramp.elements[1].color = (0.4, 0.55, 0.25, 1.0)   # Light green (high areas)

    # Add a mid-point for sand/bunker color
    mid = ramp.elements.new(0.5)
    mid.color = (0.25, 0.42, 0.15, 1.0)  # Medium green

    tex_coord = nodes.new('ShaderNodeTexCoord')
    tex_coord.location = (-600, 0)

    separate = nodes.new('ShaderNodeSeparateXYZ')
    separate.location = (-400, 0)

    map_range = nodes.new('ShaderNodeMapRange')
    map_range.location = (-200, 0)
    map_range.inputs['From Min'].default_value = meta["elevation_min"]
    map_range.inputs['From Max'].default_value = meta["elevation_max"]

    # Link the nodes together
    links.new(tex_coord.outputs['Object'], separate.inputs['Vector'])
    links.new(separate.outputs['Z'], map_range.inputs['Value'])
    links.new(map_range.outputs['Result'], color_ramp.inputs['Fac'])
    links.new(color_ramp.outputs['Color'], bsdf.inputs['Base Color'])
    links.new(bsdf.outputs['BSDF'], output.inputs['Surface'])

    # Assign material to terrain
    if terrain.data.materials:
        terrain.data.materials[0] = mat
    else:
        terrain.data.materials.append(mat)

    print("[import_dem] Applied elevation preview material")


def add_reference_grid(meta):
    """
    Add a reference grid showing 100m intervals for scale verification.
    This helps confirm the terrain dimensions are correct.
    """
    width = meta["real_width_m"] * SCALE_FACTOR
    height = meta["real_height_m"] * SCALE_FACTOR
    grid_spacing = 100.0 * SCALE_FACTOR  # 100-meter grid

    # Create a collection for reference objects
    if "Reference" not in bpy.data.collections:
        ref_collection = bpy.data.collections.new("Reference")
        bpy.context.scene.collection.children.link(ref_collection)
    else:
        ref_collection = bpy.data.collections["Reference"]

    # Create grid lines using a mesh
    mesh = bpy.data.meshes.new("TerrainGrid")
    obj = bpy.data.objects.new("TerrainGrid", mesh)
    ref_collection.objects.link(obj)

    bm = bmesh.new()

    # Vertical lines (along Y axis)
    x = 0
    while x <= width:
        v1 = bm.verts.new((x, 0, meta["elevation_max"] + 2))
        v2 = bm.verts.new((x, height, meta["elevation_max"] + 2))
        bm.edges.new((v1, v2))
        x += grid_spacing

    # Horizontal lines (along X axis)
    y = 0
    while y <= height:
        v1 = bm.verts.new((0, y, meta["elevation_max"] + 2))
        v2 = bm.verts.new((width, y, meta["elevation_max"] + 2))
        bm.edges.new((v1, v2))
        y += grid_spacing

    bm.to_mesh(mesh)
    bm.free()

    # Create a wireframe material for the grid
    grid_mat = bpy.data.materials.new("GridMaterial")
    grid_mat.use_nodes = True
    grid_mat.node_tree.nodes["Principled BSDF"].inputs['Base Color'].default_value = (1, 1, 1, 1)
    grid_mat.node_tree.nodes["Principled BSDF"].inputs['Alpha'].default_value = 0.3
    grid_mat.blend_method = 'BLEND' if hasattr(grid_mat, 'blend_method') else None
    obj.data.materials.append(grid_mat)

    print(f"[import_dem] Added {int(width/grid_spacing)+1}x{int(height/grid_spacing)+1} reference grid (100m spacing)")


def add_scale_markers(meta):
    """
    Add scale marker objects at known positions for verification.
    Places small cubes at 0m, 100m, and the full extent along each axis.
    """
    width = meta["real_width_m"] * SCALE_FACTOR
    height = meta["real_height_m"] * SCALE_FACTOR
    z_top = meta["elevation_max"] * SCALE_FACTOR + 5

    if "Reference" not in bpy.data.collections:
        ref_collection = bpy.data.collections.new("Reference")
        bpy.context.scene.collection.children.link(ref_collection)
    else:
        ref_collection = bpy.data.collections["Reference"]

    markers = [
        ("Origin_0_0", (0, 0, z_top)),
        ("Mark_100m_X", (100, 0, z_top)),
        ("Mark_100m_Y", (0, 100, z_top)),
        ("Mark_MaxX", (width, 0, z_top)),
        ("Mark_MaxY", (0, height, z_top)),
        ("Mark_Corner", (width, height, z_top)),
    ]

    marker_mat = bpy.data.materials.new("MarkerMaterial")
    marker_mat.use_nodes = True
    marker_mat.node_tree.nodes["Principled BSDF"].inputs['Base Color'].default_value = (1, 0, 0, 1)
    marker_mat.node_tree.nodes["Principled BSDF"].inputs['Emission Color'].default_value = (1, 0, 0, 1)
    marker_mat.node_tree.nodes["Principled BSDF"].inputs['Emission Strength'].default_value = 2.0

    for name, loc in markers:
        bpy.ops.mesh.primitive_cube_add(size=3.0, location=loc)
        marker = bpy.context.active_object
        marker.name = name

        # Move to reference collection
        for col in marker.users_collection:
            col.objects.unlink(marker)
        ref_collection.objects.link(marker)

        marker.data.materials.append(marker_mat)

    print("[import_dem] Added scale markers at key positions")


def setup_camera(meta):
    """
    Set up an overhead camera looking down at the course.
    Good for verifying the terrain import before detailed modeling.
    """
    width = meta["real_width_m"] * SCALE_FACTOR
    height = meta["real_height_m"] * SCALE_FACTOR
    center_x = width / 2
    center_y = height / 2
    cam_height = max(width, height) * 1.2  # High enough to see the whole course

    # Check if camera exists, otherwise create one
    if "OverheadCamera" in bpy.data.objects:
        cam_obj = bpy.data.objects["OverheadCamera"]
    else:
        cam_data = bpy.data.cameras.new("OverheadCamera")
        cam_obj = bpy.data.objects.new("OverheadCamera", cam_data)
        bpy.context.scene.collection.objects.link(cam_obj)

    cam_obj.location = (center_x, center_y, meta["elevation_max"] + cam_height)
    cam_obj.rotation_euler = (0, 0, 0)  # Looking straight down

    # Set as active camera
    bpy.context.scene.camera = cam_obj

    # Use orthographic projection for accurate top-down view
    cam_obj.data.type = 'ORTHO'
    cam_obj.data.ortho_scale = max(width, height) * 1.1

    print(f"[import_dem] Camera set up: overhead at ({center_x:.0f}, {center_y:.0f}), "
          f"height {cam_height:.0f}m")


def setup_viewport(terrain):
    """
    Configure viewport settings for good terrain visualization.
    Switches to Material Preview mode so the elevation colors are visible.
    """
    # Set viewport shading to Material Preview
    for area in bpy.context.screen.areas:
        if area.type == 'VIEW_3D':
            for space in area.spaces:
                if space.type == 'VIEW_3D':
                    space.shading.type = 'MATERIAL'
                    space.shading.use_scene_lights = True
                    space.shading.use_scene_world = False

                    # Set clip distance for large terrains
                    space.clip_start = 0.1
                    space.clip_end = 10000.0

                    # Frame the terrain in the viewport
                    # Select the terrain and use "View Selected"
                    bpy.context.view_layer.objects.active = terrain
                    terrain.select_set(True)

    # Try to frame the view (may not work in all contexts)
    try:
        bpy.ops.view3d.view_selected()
    except RuntimeError:
        pass  # Not in a 3D viewport context (e.g., running from command line)

    print("[import_dem] Viewport configured for terrain visualization")


def add_sun_light(meta):
    """
    Add a sun light for basic illumination.
    Positioned to simulate late-morning light from the southeast,
    which is typical for golf course visualization.
    """
    width = meta["real_width_m"] * SCALE_FACTOR
    height = meta["real_height_m"] * SCALE_FACTOR

    # Remove existing sun if present
    if "CourseSun" in bpy.data.objects:
        bpy.data.objects.remove(bpy.data.objects["CourseSun"], do_unlink=True)

    light_data = bpy.data.lights.new(name="CourseSun", type='SUN')
    light_data.energy = 3.0
    light_data.color = (1.0, 0.95, 0.9)  # Slightly warm

    sun = bpy.data.objects.new("CourseSun", light_data)
    bpy.context.scene.collection.objects.link(sun)

    # Position doesn't matter for sun lights (they're directional),
    # but the rotation controls the light direction
    sun.location = (width / 2, height / 2, meta["elevation_max"] + 100)
    sun.rotation_euler = (math.radians(45), math.radians(15), math.radians(135))

    print("[import_dem] Added sun light (late-morning angle)")


# ---------------------------------------------------------------------------
# File dialog operator — this is what runs when the user executes the script
# ---------------------------------------------------------------------------

class IMPORT_OT_heightmap(bpy.types.Operator):
    """Import a heightmap PNG as terrain mesh for OPCD course building"""
    bl_idname = "import_scene.heightmap_dem"
    bl_label = "Import Heightmap DEM"
    bl_options = {'REGISTER', 'UNDO'}

    # File browser properties
    filepath: bpy.props.StringProperty(
        subtype='FILE_PATH',
        default="",
    )

    filter_glob: bpy.props.StringProperty(
        default="*.png;*.tif;*.tiff",
        options={'HIDDEN'},
    )

    # Option: use vertex displacement instead of modifier
    use_vertex_displacement: bpy.props.BoolProperty(
        name="Direct Vertex Displacement",
        description="Modify vertices directly instead of using a modifier. "
                    "More reliable for export but slower to apply",
        default=False,
    )

    def execute(self, context):
        if not self.filepath:
            self.report({'ERROR'}, "No file selected")
            return {'CANCELLED'}

        print(f"\n{'='*60}")
        print(f"  IMPORTING HEIGHTMAP: {self.filepath}")
        print(f"{'='*60}\n")

        # Step 1: Load metadata
        meta = load_metadata(self.filepath)
        print(f"[import_dem] Real dimensions: {meta['real_width_m']:.0f}m x {meta['real_height_m']:.0f}m")
        print(f"[import_dem] Elevation: {meta['elevation_min']:.1f}m - {meta['elevation_max']:.1f}m")

        # Step 2: Clean up any existing terrain
        cleanup_existing()

        # Step 3: Load the heightmap image
        heightmap_img = load_heightmap_image(self.filepath)
        img_w, img_h = heightmap_img.size

        # Step 4: Calculate subdivision level
        subdiv_level = calculate_subdivisions(img_w, img_h)

        # Step 5: Create the terrain plane
        terrain = create_terrain_plane(meta)

        # Step 6: Subdivide the terrain
        subdivide_terrain(terrain, subdiv_level)

        # Step 7: Apply displacement
        if self.use_vertex_displacement:
            apply_displacement_via_vertices(terrain, heightmap_img, meta)
        else:
            apply_displacement_texture(terrain, heightmap_img, meta)

        # Step 8: Add visualization material
        setup_terrain_material(terrain, heightmap_img, meta)

        # Step 9: Add reference objects
        add_reference_grid(meta)
        add_scale_markers(meta)

        # Step 10: Set up camera
        setup_camera(meta)

        # Step 11: Add lighting
        add_sun_light(meta)

        # Step 12: Configure viewport
        setup_viewport(terrain)

        # Step 13: Set Blender scene units to metric
        context.scene.unit_settings.system = 'METRIC'
        context.scene.unit_settings.scale_length = 1.0
        context.scene.unit_settings.length_unit = 'METERS'

        print(f"\n{'='*60}")
        print(f"  TERRAIN IMPORT COMPLETE")
        print(f"  Dimensions: {meta['real_width_m']:.0f}m x {meta['real_height_m']:.0f}m")
        print(f"  Elevation range: {meta['elevation_max'] - meta['elevation_min']:.1f}m")
        print(f"  Vertices: {len(terrain.data.vertices):,}")
        print(f"{'='*60}\n")

        self.report({'INFO'}, f"Terrain imported: {meta['real_width_m']:.0f}x{meta['real_height_m']:.0f}m")
        return {'FINISHED'}

    def invoke(self, context, event):
        # Open file browser dialog
        context.window_manager.fileselect_add(self)
        return {'RUNNING_MODAL'}


# ---------------------------------------------------------------------------
# Registration — allows running from Blender's menu
# ---------------------------------------------------------------------------

def menu_func_import(self, context):
    self.layout.operator(IMPORT_OT_heightmap.bl_idname, text="Heightmap DEM (.png)")


def register():
    bpy.utils.register_class(IMPORT_OT_heightmap)
    bpy.types.TOPBAR_MT_file_import.append(menu_func_import)


def unregister():
    bpy.utils.unregister_class(IMPORT_OT_heightmap)
    bpy.types.TOPBAR_MT_file_import.remove(menu_func_import)


# ---------------------------------------------------------------------------
# Main — when run directly from Blender's text editor
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    register()

    # Check if a filepath was passed as argument (e.g., from command line)
    # Usage: blender --python import_dem.py -- /path/to/heightmap.png
    argv = sys.argv
    if "--" in argv:
        custom_args = argv[argv.index("--") + 1:]
        if custom_args:
            filepath = custom_args[0]
            if os.path.exists(filepath):
                print(f"[import_dem] Using command-line filepath: {filepath}")
                bpy.ops.import_scene.heightmap_dem(filepath=filepath)
            else:
                print(f"[import_dem] File not found: {filepath}")
                print("[import_dem] Opening file dialog instead...")
                bpy.ops.import_scene.heightmap_dem('INVOKE_DEFAULT')
        else:
            bpy.ops.import_scene.heightmap_dem('INVOKE_DEFAULT')
    else:
        # No command line args — open file dialog
        bpy.ops.import_scene.heightmap_dem('INVOKE_DEFAULT')
